server.port=8080

spring.application.name=inkwell-web
spring.web.cors.allowed-origins: "*"
services:
  auth:     http://localhost:8081
  post:     http://localhost:8082
  comment:  http://localhost:8083
  category: http://localhost:8084
  media:    http://localhost:8085
  newsletter: http://localhost:8086
  notification: http://localhost:8087
jwt.secret= 7osPC6OuB6osqKa70kTZxHB9yZp64N5LJu03p9gJfWk=
springdoc.api-docs.path= /api-docs
springdoc.swagger-ui.path= /swagger-ui.html